spring:
  application:
    name: serviceconfig
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: ${CONFIG_LOCATION:file:////config }
    
server:
  port: ${PORT:8888}
 
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_ZONE:http://127.0.0.1:8761/eureka/}    
