name: Docker build and publish image to github
on: 
  push:
    tags: 
      - '*g'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests=true
      
    - name: Build and publish Docker Image to GitHub Packages Registry
      uses: VaultVulp/gp-docker-action@1.1.7
      with:
        github-token: ${{ github.token }}
        image-name: serviceconfig
        image-tag: latest
        extract-git-tag: false
        dockerfile: Dockerfile
        build-context: .
        pull-image: false
